# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'stuff of minsun'
tagline:          'more stuff'
description:      'many stuff'
url:              http://www.stuffofminsun.com
baseurl:          http://www.stuffofminsun.com/

author:
  name:           'Minsun'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
timezone:         America/New_York
