# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            much stuff
tagline:          many stuff
description:      'A page of stuff. I'm not that imaginative with urls.'
url:              http://www.stuffofminsun.com
baseurl:          /

author:
  name:           'Minsun'
  url:            

paginate:         5

# Custom vars
version:          

github:
  repo:           https://github.com/stuffofminsun
