# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'stuff of minsun'
tagline:          'many stuff'
description:      'just stuff'
url:              https://www.stuffofminsun.com
baseurl:          https://www.stuffofminsun.com/

author:
  name:           'Minsun'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
timezone:         America/New_York

analytics:
  provider:      'google-gtag'
  google:
    tracking_id: 'UA-138680040-1'
    anonymize_ip:false